name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]
    if: always()

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Make sure Python is available
      - uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install the package in dev mode
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run all tests
        run: pytest -v .

